### ISSUE TITLE
4.2 regression checklist

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/muffin#519]
- [ ] Restoring maximized slack from systray leads to non-maximized slack, with glitching
- [ ] Artefacts in window list
- [ ] Crash in meta_window_should_unredirect

**Comment by jaszhix** [comment]
I don't really feel motivated to fix completely new bugs caused by a revert of something I spent the last 6 months of my life on.

**Comment by jaszhix** [comment]
How do you know Bug 1 is any more difficult than the petty effects blemishes that blocked a FAST compositing experience for people? These mapping bugs have been a serious pain, and I was counting on the revert being done smoothly enough so we were fixing minor things. This isn't the branch I was testing the other day. Then you seemed to insta-merge a bunch of things, and then throw up this checklist.

Also, having to defend the REMOVAL of the gulp scripts from the Cinnamon repos - which was the driving motivation for me making extensions load asynchronously in 3.8. COMPLETELY unfair to me. I will not contribute under these circumstances. Please roll back master, or prepare a revert that isn't a nightmare.

**Comment by mtwebster** [comment]
I went back as far as 3.8 and got identical behavior with item 1, so i don't think it's new.  Well, it's new to us I suppose :)

**Comment by clefebvre** [comment]
Ok I should rephrase it then. @JosephMcc is seeing unresponsive content inside the slack window, as if the widgets were in a different place than where they appear. I tried to reproduce and thought this was the same issue.

**Comment by clefebvre** [comment]
I'll start bissecting all these on Monday to understand when they started to appear. I'm really surprised to see the lock screen issue here. I was pretty sure it was gone in iter-20/revert-20.

**Comment by JosephMcc** [comment]
Just to clear this up, I think the source of my problem was the notification area being blocked from input. The latest updates to master seem to have straightened this out and I think it my misunderstanding of what was happening.
